### ISSUE TITLE
Writable Ole Automation properties are exposed as frozen in Javascript

### ISSUE THREAD

**Issue by vbousquet** [mjrgh/PinballY#110]
**Describe the bug**
When using the javascript capabilities (main.js in Scripts folder), if you create an Ole Automation object through the ```createAutomationObject```, the wrapper will wrap all its properties as **frozen**, even if they have a setter.

**To Reproduce**
1. Create a script 'main.js' which create an automation object with a known writable property. For example, ```Scripting.Dictionary```
2. Try to write to the writable property
4. See error "TypeError: Assignment to read-only properties is not allowed in strict mode" in the log file

**Expected behavior**
You should be able to write to writable properties.

**Test files**
Here is an exemple main.js that will display the problem (frozen properties) and trigger the error:
```javascript
function getMethods(obj) {
  var result = [];
  for (var id in obj) {
    try {
        result.push(id + ": " + obj[id].toString() + " / frozen=" + Object.isFrozen(obj[id]) + " / sealed=" + Object.isSealed(obj[id]) + " / type=" + typeof(obj[id]));
    } catch (err) {
      result.push(id + ": inaccessible");
    }
  }
  return result;
}

let dict = createAutomationObject("Scripting.Dictionary");
logfile.log(getMethods(dict).join("\n"));
dict.CompareMode = 1;
```

**Screenshots**
Not a screenshot, but the log output of the above code;
```
[Javascript] Loading module from file ...\scripts\main.js
[Script] Item: function (...args) { return dllImport._invokeAutomationMethod(this, funcIndex, dispType, ...args); } / frozen=false / sealed=false / type=function
Add: function (...args) { return dllImport._invokeAutomationMethod(this, funcIndex, dispType, ...args); } / frozen=false / sealed=false / type=function
Exists: function (...args) { return dllImport._invokeAutomationMethod(this, funcIndex, dispType, ...args); } / frozen=false / sealed=false / type=function
Items: function (...args) { return dllImport._invokeAutomationMethod(this, funcIndex, dispType, ...args); } / frozen=false / sealed=false / type=function
Key: function (...args) { return dllImport._invokeAutomationMethod(this, funcIndex, dispType, ...args); } / frozen=false / sealed=false / type=function
Keys: function (...args) { return dllImport._invokeAutomationMethod(this, funcIndex, dispType, ...args); } / frozen=false / sealed=false / type=function
Remove: function (...args) { return dllImport._invokeAutomationMethod(this, funcIndex, dispType, ...args); } / frozen=false / sealed=false / type=function
RemoveAll: function (...args) { return dllImport._invokeAutomationMethod(this, funcIndex, dispType, ...args); } / frozen=false / sealed=false / type=function
CompareMode: 0 / frozen=true / sealed=true / type=number
Count: 0 / frozen=true / sealed=true / type=number
[Javascript] Error executing module D:\Games\PinballY\scripts\main.js

[Javascript]: Uncaught exception:
TypeError: Assignment to read-only properties is not allowed in strict mode
   at Anonymous function (file:///...\PinballY\Scripts\main.js:18:1)
   at module (file:///...\PinballY\Scripts\main.js:2:1)
```

**Windows version**
Windows 10 x64. Tested both for the x86 & x64 versions of PinballY.

**Additional context**
Beside the example given here, this has been tested with other objects from my project ([FlexDMD, OpenSource DMD graphic library](https://github.com/vbousquet/flexdmd)) without any luck whatever the properties type & definition.

**Comment by vbousquet** [comment]
Yesterday commit a5828db174e0d6d7eff552cdf2a676a90559553c fixes this. Thanks a lot!
