### ISSUE TITLE
PinballY fails to start when using 1.8 beta freezy dlls

### ISSUE THREAD

**Issue by jsb2092** [mjrgh/PinballY#122]
When using the DMDdevice64.dll from flexdmd (found here: https://github.com/vbousquet/flexdmd/releases), PinballY crashes on startup.

**Comment by mjrgh** [comment]
Maybe let Freezy know about it, and see if he can try it in the debugger to see if it's a crash in the DLL.

**Comment by jsb2092** [comment]
Oh, I am on it.  Just thought you’d want to know too.

On Mar 16, 2020, at 23:04, mjrgh <notifications@github.com> wrote:

﻿

Maybe let Freezy know about it, and see if he can try it in the debugger to see if it's a crash in the DLL.

**Comment by mkalkbrenner** [comment]
I used the latest build artefarct of freezy's DLL when I recorded this video:
https://youtu.be/g18_2WF7xis

So far, no crashes in this combination PinballY/freezy's DLL/FlexDMD

**Comment by jsb2092** [comment]
Ok, I put the dmdDevice64.dll in my VPinMame directory and when I did that, PinballY would fail to start.  I changed nothing else. When I reverted to the previous version (1.71), it started again with no issues.  I did not use the scripts provided for flexdmd (though they look really cool)

**Comment by mkalkbrenner** [comment]
Do you use a real DMD?

**Comment by jsb2092** [comment]
Yes, using a PinDMD3.

**Comment by mkalkbrenner** [comment]
If you use FlexDMD you should integrate it with PinballY using the javascript: https://github.com/vbousquet/flexdmd/tree/master/Scripts/PinballY

In PinballY you should disable the real DMD support

**Comment by jsb2092** [comment]
I did, it's awesome - doesn't fix the issue with it crashing with the 1.8 beta though :(

**Comment by mjrgh** [comment]
>>In PinballY you should disable the real DMD support
> I did, it's awesome - doesn't fix the issue with it crashing with the 1.8 beta though :(

Hang on a sec, you're saying that you **disabled Real DMD** in PinballY?  In that case, you should be aware that PinballY **doesn't load the DMD DLL at all**.  So the crash pretty much can't be coming from a PinballY interaction - it must be somewhere else.

**Comment by jsb2092** [comment]
No, I enabled the script - still have the DMD integration, however, when I attempt to load pinballY with the 1.8 beta freezy dll, it crashed, the 1.71 does not crash, and the script still works and is awesome.

**Comment by mjrgh** [comment]
My point is that PinballY isn't loading the Freezy DLL if you set "Disable Real DMD" in the options.  Make sense?

**Comment by jsb2092** [comment]
Yes, that makes sense - but I didn't disable it, so it's trying to load the 1.8 DLL which does crash.

**Comment by mjrgh** [comment]
Oh, I see - I thought you said above that you disabled it.  Nevermind.

**Comment by mkalkbrenner** [comment]
@jsb2092 If you use FlexDMD you should disable the real DMD in PinballY. I guess that this avoid your crash.

But
@mjrgh if he's right, there might be an issue with the latest build of Freezy's DLL in combination with PinballY. This is not related to FlexDMD. But FlexDMD ships the latest DLLs.

**Comment by jsb2092** [comment]
I will try disabling it - but yes, there is an issue, because I wasn't using the FlexDMD scripts in PinballY and it crashed.  I don't think it's an issue with FlexDMD, and I appreciated being able to try out the 1.8 beta, since I hadn't seen it elsewhere.

**Comment by mjrgh** [comment]
> if he's right, there might be an issue with the latest build of Freezy's DLL in combination with PinballY.

Quite possible - but for now, I'm treating it as a Freezy bug, since presumably whatever changed is on the Freezy side.

**Comment by jsb2092** [comment]
Agreed, I just wanted to get it on your radar.

**Comment by intelmation** [comment]
As long as I have DMD set to Auto, or Enabled, PinballY will crash on open (and close itself). I have to manually go into settings and set DMD to Off to get the application to run again.

By putting the patched .dll in my PinMame folder, the program crashes on open (closes itself) but I can re-open the program without DMD enabled selected...

I have Windows 10 Pro 64-bit and a PIN2DMD.

**Comment by usul27** [comment]
I also have an issue here when starting the 64bit version. It just crashes:

[1] 2021/01/23 11:58:40.031 ERROR | System.TypeInitializationException: The type initializer for 'LibDmd.Output.Virtual.AlphaNumeric.VirtualAlphanumericDestination' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libSkiaSharp': Das angegebene Modul wurde nicht gefunden. (Exception from HRESULT: 0x8007007E)
   at SkiaSharp.SkiaApi.sk_picture_recorder_new()
   at SkiaSharp.SKPictureRecorder..ctor()
   at SkiaSharp.Extended.Svg.SKSvg.Load(XDocument xdoc)
   at SkiaSharp.Extended.Svg.SKSvg.Load(Stream stream)
   at LibDmd.Output.Virtual.AlphaNumeric.AlphaNumericResources.Load(String[] fileNames, String pathToFull, SegmentType type, SegmentWeight weight) in C:\Development\dmd-extensions\LibDmd\Output\Virtual\AlphaNumeric\AlphaNumericResources.cs:line 306
   at LibDmd.Output.Virtual.AlphaNumeric.AlphaNumericResources.LoadAlphaNumeric(SegmentWeight weight) in C:\Development\dmd-extensions\LibDmd\Output\Virtual\AlphaNumeric\AlphaNumericResources.cs:line 264
   at LibDmd.Output.Virtual.AlphaNumeric.AlphaNumericResources..ctor() in C:\Development\dmd-extensions\LibDmd\Output\Virtual\AlphaNumeric\AlphaNumericResources.cs:line 214
   at LibDmd.Output.Virtual.AlphaNumeric.AlphaNumericResources.GetInstance() in C:\Development\dmd-extensions\LibDmd\Output\Virtual\AlphaNumeric\AlphaNumericResources.cs:line 93
   at LibDmd.Output.Virtual.AlphaNumeric.VirtualAlphanumericDestination..cctor() in C:\Development\dmd-extensions\LibDmd\Output\Virtual\AlphaNumeric\VirtualAlphanumericDestination.cs:line 20
   --- End of inner exception stack trace ---
   at LibDmd.Output.Virtual.AlphaNumeric.VirtualAlphanumericDestination.GetInstance(Dispatcher dispatcher, RasterizeStyleDefinition styleDef, Configuration config) in C:\Development\dmd-extensions\LibDmd\Output\Virtual\AlphaNumeric\VirtualAlphanumericDestination.cs:line 44
   at LibDmd.DmdDevice.DmdDevice.SetupGraphs() in C:\Development\dmd-extensions\LibDmd\DmdDevice\DmdDevice.cs:line 312
   at LibDmd.DmdDevice.DmdDevice.Init() in C:\Development\dmd-extensions\LibDmd\DmdDevice\DmdDevice.cs:line 168
   at LibDmd.DmdDevice.DmdDevice.RenderGray4(DMDFrame frame) in C:\Development\dmd-extensions\LibDmd\DmdDevice\DmdDevice.cs:line 636 

Looks like some missing library

**Comment by mjrgh** [comment]
> Looks like some missing library

Yes it does - you should contact freezy about that, since all of those errors are coming from his stuff ("LibDMD" is part of dmd-extensions).

**Comment by xantari** [comment]
@usul27 That libskia library issue should be fixed now in the latest pre-release 1.9.0 builds.

Here are the referenced issues:

https://github.com/freezy/dmd-extensions/issues/212
https://github.com/freezy/dmd-extensions/issues/252

Pretty sure this whole issue is likely no longer a problem if you use the latest 1.9.0 release you can find here:

https://ci.appveyor.com/project/freezy/dmd-extensions/history

**Comment by mjrgh** [comment]
@xantari - fantastic, thanks.  I'll mark this as closed.
